version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_DATABASE: meteo
      MYSQL_USER: user
      MYSQL_PASSWORD: Test123
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"  # Adjust the port if your Node.js app runs on a different port
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: Test123
      DB_NAME: meteo
    command: >
      /bin/bash -c "
      npm install && npm start
      "